spring:
  application:
    name: @project.name@
    version: @project.version@
  datasource:
    url: jdbc:h2:file:/data/assembleia-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
  console:
    enabled: true
    path: /h2-console
    settings.trace: false
    settings.web-allow-others: false
server:
  port: 8080
  servlet:
    context-path: /poc/v1
logging:
  level:
    project:
      user:
        UserClient: DEBUG
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
